version: '3.8'

services:
  # (SQL Server)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: news_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong_Password_123!
    ports:
      - "1433:1433"
    networks:
      - news-net

  # (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: news_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - news-net

  #(Redis)
  redis:
    image: redis:alpine
    container_name: news_redis
    ports:
      - "6379:6379"
    networks:
      - news-net

  # (Elasticsearch)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: news_elastic
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - news-net

  # (Kibana - Opsiyonel ama analiz için iyidir)
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: news_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - news-net

networks:
  news-net:
    driver: bridge